name: Publish Docker image

on:
  release:
    types: [published]

permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: "sand14"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sand14/bibescu-app

      - name: Build and Push Multi-Platform Image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: sand14/bibescu-app
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true