name: Docker Image CI for GHCR

on:
  workflow_dispatch:

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub Container Registry
        uses: docker/login-action@v2
        with:
          username: "sand14"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Multi-Platform Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sand14/bibescu-app:latest
          platforms: linux/arm64